/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sudokux;

import java.awt.Component;
import javax.swing.JTextField;

/**
 *
 * @author dvarg
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tablero = new javax.swing.JPanel();
        Matrix0 = new javax.swing.JPanel();
        P0_0 = new javax.swing.JTextField();
        P0_1 = new javax.swing.JTextField();
        P0_2 = new javax.swing.JTextField();
        P1_0 = new javax.swing.JTextField();
        P1_1 = new javax.swing.JTextField();
        P1_2 = new javax.swing.JTextField();
        P2_0 = new javax.swing.JTextField();
        P2_1 = new javax.swing.JTextField();
        P2_2 = new javax.swing.JTextField();
        Matrix1 = new javax.swing.JPanel();
        P0_3 = new javax.swing.JTextField();
        P0_4 = new javax.swing.JTextField();
        P0_5 = new javax.swing.JTextField();
        P1_3 = new javax.swing.JTextField();
        P1_4 = new javax.swing.JTextField();
        P1_5 = new javax.swing.JTextField();
        P2_3 = new javax.swing.JTextField();
        P2_4 = new javax.swing.JTextField();
        P2_5 = new javax.swing.JTextField();
        Matrix2 = new javax.swing.JPanel();
        P0_6 = new javax.swing.JTextField();
        P0_7 = new javax.swing.JTextField();
        P0_8 = new javax.swing.JTextField();
        P1_6 = new javax.swing.JTextField();
        P1_7 = new javax.swing.JTextField();
        P1_8 = new javax.swing.JTextField();
        P2_6 = new javax.swing.JTextField();
        P2_7 = new javax.swing.JTextField();
        P2_8 = new javax.swing.JTextField();
        Matrix3 = new javax.swing.JPanel();
        P3_0 = new javax.swing.JTextField();
        P3_1 = new javax.swing.JTextField();
        P3_2 = new javax.swing.JTextField();
        P4_0 = new javax.swing.JTextField();
        P4_1 = new javax.swing.JTextField();
        P4_2 = new javax.swing.JTextField();
        P5_0 = new javax.swing.JTextField();
        P5_1 = new javax.swing.JTextField();
        P5_2 = new javax.swing.JTextField();
        Matrix4 = new javax.swing.JPanel();
        P3_3 = new javax.swing.JTextField();
        P3_4 = new javax.swing.JTextField();
        P3_5 = new javax.swing.JTextField();
        P4_3 = new javax.swing.JTextField();
        P4_4 = new javax.swing.JTextField();
        P4_5 = new javax.swing.JTextField();
        P5_3 = new javax.swing.JTextField();
        P5_4 = new javax.swing.JTextField();
        P5_5 = new javax.swing.JTextField();
        Matrix5 = new javax.swing.JPanel();
        P3_6 = new javax.swing.JTextField();
        P3_7 = new javax.swing.JTextField();
        P3_8 = new javax.swing.JTextField();
        P4_6 = new javax.swing.JTextField();
        P4_7 = new javax.swing.JTextField();
        P4_8 = new javax.swing.JTextField();
        P5_6 = new javax.swing.JTextField();
        P5_7 = new javax.swing.JTextField();
        P5_8 = new javax.swing.JTextField();
        Matrix6 = new javax.swing.JPanel();
        P6_0 = new javax.swing.JTextField();
        P6_1 = new javax.swing.JTextField();
        P6_2 = new javax.swing.JTextField();
        P7_0 = new javax.swing.JTextField();
        P7_1 = new javax.swing.JTextField();
        P7_2 = new javax.swing.JTextField();
        P8_0 = new javax.swing.JTextField();
        P8_1 = new javax.swing.JTextField();
        P8_2 = new javax.swing.JTextField();
        Matrix7 = new javax.swing.JPanel();
        P6_3 = new javax.swing.JTextField();
        P6_4 = new javax.swing.JTextField();
        P6_5 = new javax.swing.JTextField();
        P7_3 = new javax.swing.JTextField();
        P7_4 = new javax.swing.JTextField();
        P7_5 = new javax.swing.JTextField();
        P8_3 = new javax.swing.JTextField();
        P8_4 = new javax.swing.JTextField();
        P8_5 = new javax.swing.JTextField();
        Matrix8 = new javax.swing.JPanel();
        P6_6 = new javax.swing.JTextField();
        P6_7 = new javax.swing.JTextField();
        P6_8 = new javax.swing.JTextField();
        P7_6 = new javax.swing.JTextField();
        P7_7 = new javax.swing.JTextField();
        P7_8 = new javax.swing.JTextField();
        P8_6 = new javax.swing.JTextField();
        P8_7 = new javax.swing.JTextField();
        P8_8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tablero.setPreferredSize(new java.awt.Dimension(600, 600));

        Matrix0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix0.setPreferredSize(new java.awt.Dimension(200, 200));

        P0_0.setBackground(new java.awt.Color(204, 204, 204));
        P0_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P0_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P0_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P0_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P0_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_1.setBackground(new java.awt.Color(204, 204, 204));
        P1_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_1.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_1.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_2.setBackground(new java.awt.Color(204, 204, 204));
        P2_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix0Layout = new javax.swing.GroupLayout(Matrix0);
        Matrix0.setLayout(Matrix0Layout);
        Matrix0Layout.setHorizontalGroup(
            Matrix0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix0Layout.createSequentialGroup()
                .addComponent(P0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P0_1)
                .addGap(0, 0, 0)
                .addComponent(P0_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix0Layout.createSequentialGroup()
                .addComponent(P1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Matrix0Layout.createSequentialGroup()
                .addComponent(P2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix0Layout.setVerticalGroup(
            Matrix0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix0Layout.createSequentialGroup()
                .addGroup(Matrix0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P0_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Matrix1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix1.setPreferredSize(new java.awt.Dimension(200, 200));

        P0_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P0_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P0_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P0_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P0_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P0_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix1Layout = new javax.swing.GroupLayout(Matrix1);
        Matrix1.setLayout(Matrix1Layout);
        Matrix1Layout.setHorizontalGroup(
            Matrix1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix1Layout.createSequentialGroup()
                .addComponent(P0_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P0_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P0_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix1Layout.createSequentialGroup()
                .addComponent(P1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix1Layout.createSequentialGroup()
                .addComponent(P2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix1Layout.setVerticalGroup(
            Matrix1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix1Layout.createSequentialGroup()
                .addGroup(Matrix1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P0_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P0_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P0_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Matrix2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix2.setPreferredSize(new java.awt.Dimension(200, 200));

        P0_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P0_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P0_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P0_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P0_8.setBackground(new java.awt.Color(204, 204, 204));
        P0_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P0_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P0_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P0_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_7.setBackground(new java.awt.Color(204, 204, 204));
        P1_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P1_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P1_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P1_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_6.setBackground(new java.awt.Color(204, 204, 204));
        P2_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P2_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P2_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P2_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix2Layout = new javax.swing.GroupLayout(Matrix2);
        Matrix2.setLayout(Matrix2Layout);
        Matrix2Layout.setHorizontalGroup(
            Matrix2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix2Layout.createSequentialGroup()
                .addComponent(P0_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P0_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P0_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix2Layout.createSequentialGroup()
                .addComponent(P1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P1_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix2Layout.createSequentialGroup()
                .addComponent(P2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P2_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P2_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix2Layout.setVerticalGroup(
            Matrix2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix2Layout.createSequentialGroup()
                .addGroup(Matrix2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P0_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P0_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P0_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Matrix3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix3.setPreferredSize(new java.awt.Dimension(200, 200));

        P3_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P3_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_1.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P3_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_1.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_1.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix3Layout = new javax.swing.GroupLayout(Matrix3);
        Matrix3.setLayout(Matrix3Layout);
        Matrix3Layout.setHorizontalGroup(
            Matrix3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix3Layout.createSequentialGroup()
                .addComponent(P3_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix3Layout.createSequentialGroup()
                .addComponent(P4_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix3Layout.createSequentialGroup()
                .addComponent(P5_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P5_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P5_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix3Layout.setVerticalGroup(
            Matrix3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix3Layout.createSequentialGroup()
                .addGroup(Matrix3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P3_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P4_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P5_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P5_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P5_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Matrix4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix4.setPreferredSize(new java.awt.Dimension(200, 200));

        P3_3.setBackground(new java.awt.Color(204, 204, 204));
        P3_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P3_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P3_5.setBackground(new java.awt.Color(204, 204, 204));
        P3_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_4.setBackground(new java.awt.Color(204, 204, 204));
        P4_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_3.setBackground(new java.awt.Color(204, 204, 204));
        P5_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_5.setBackground(new java.awt.Color(204, 204, 204));
        P5_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix4Layout = new javax.swing.GroupLayout(Matrix4);
        Matrix4.setLayout(Matrix4Layout);
        Matrix4Layout.setHorizontalGroup(
            Matrix4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix4Layout.createSequentialGroup()
                .addComponent(P3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix4Layout.createSequentialGroup()
                .addComponent(P4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix4Layout.createSequentialGroup()
                .addComponent(P5_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P5_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P5_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix4Layout.setVerticalGroup(
            Matrix4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix4Layout.createSequentialGroup()
                .addGroup(Matrix4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P5_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P5_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P5_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Matrix5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix5.setPreferredSize(new java.awt.Dimension(200, 200));

        P3_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P3_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P3_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P3_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P3_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P4_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P4_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P4_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P5_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P5_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P5_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P5_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix5Layout = new javax.swing.GroupLayout(Matrix5);
        Matrix5.setLayout(Matrix5Layout);
        Matrix5Layout.setHorizontalGroup(
            Matrix5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix5Layout.createSequentialGroup()
                .addComponent(P3_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P3_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P3_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix5Layout.createSequentialGroup()
                .addComponent(P4_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P4_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P4_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix5Layout.createSequentialGroup()
                .addComponent(P5_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P5_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P5_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix5Layout.setVerticalGroup(
            Matrix5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix5Layout.createSequentialGroup()
                .addGroup(Matrix5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P3_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P4_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P5_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P5_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P5_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Matrix6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix6.setPreferredSize(new java.awt.Dimension(200, 200));

        P6_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P6_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_1.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P6_2.setBackground(new java.awt.Color(204, 204, 204));
        P6_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_1.setBackground(new java.awt.Color(204, 204, 204));
        P7_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_1.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_0.setBackground(new java.awt.Color(204, 204, 204));
        P8_0.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_0.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_1.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_2.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix6Layout = new javax.swing.GroupLayout(Matrix6);
        Matrix6.setLayout(Matrix6Layout);
        Matrix6Layout.setHorizontalGroup(
            Matrix6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix6Layout.createSequentialGroup()
                .addComponent(P6_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P6_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P6_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix6Layout.createSequentialGroup()
                .addComponent(P7_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P7_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P7_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix6Layout.createSequentialGroup()
                .addComponent(P8_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P8_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P8_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix6Layout.setVerticalGroup(
            Matrix6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix6Layout.createSequentialGroup()
                .addGroup(Matrix6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P6_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P6_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P6_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P7_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P7_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P7_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P8_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P8_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P8_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Matrix7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix7.setPreferredSize(new java.awt.Dimension(200, 200));

        P6_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P6_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P6_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_3.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_4.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_5.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix7Layout = new javax.swing.GroupLayout(Matrix7);
        Matrix7.setLayout(Matrix7Layout);
        Matrix7Layout.setHorizontalGroup(
            Matrix7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix7Layout.createSequentialGroup()
                .addComponent(P6_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P6_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P6_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix7Layout.createSequentialGroup()
                .addComponent(P7_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P7_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P7_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix7Layout.createSequentialGroup()
                .addComponent(P8_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P8_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P8_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix7Layout.setVerticalGroup(
            Matrix7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix7Layout.createSequentialGroup()
                .addGroup(Matrix7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P6_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P6_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P6_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P7_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P7_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P7_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P8_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P8_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P8_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Matrix8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Matrix8.setPreferredSize(new java.awt.Dimension(200, 200));

        P6_6.setBackground(new java.awt.Color(204, 204, 204));
        P6_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P6_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P6_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P6_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P6_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P6_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_7.setBackground(new java.awt.Color(204, 204, 204));
        P7_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P7_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P7_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P7_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P7_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_6.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_7.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        P8_8.setBackground(new java.awt.Color(204, 204, 204));
        P8_8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        P8_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P8_8.setPreferredSize(new java.awt.Dimension(66, 66));
        P8_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTyped(evt);
            }
        });

        javax.swing.GroupLayout Matrix8Layout = new javax.swing.GroupLayout(Matrix8);
        Matrix8.setLayout(Matrix8Layout);
        Matrix8Layout.setHorizontalGroup(
            Matrix8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix8Layout.createSequentialGroup()
                .addComponent(P6_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P6_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P6_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix8Layout.createSequentialGroup()
                .addComponent(P7_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P7_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P7_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Matrix8Layout.createSequentialGroup()
                .addComponent(P8_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P8_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P8_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Matrix8Layout.setVerticalGroup(
            Matrix8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matrix8Layout.createSequentialGroup()
                .addGroup(Matrix8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P6_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P6_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P6_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Matrix8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P7_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P7_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P7_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Matrix8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P8_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P8_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P8_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout TableroLayout = new javax.swing.GroupLayout(Tablero);
        Tablero.setLayout(TableroLayout);
        TableroLayout.setHorizontalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableroLayout.createSequentialGroup()
                .addGroup(TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(TableroLayout.createSequentialGroup()
                            .addComponent(Matrix6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Matrix7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(Matrix8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TableroLayout.createSequentialGroup()
                            .addComponent(Matrix0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Matrix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Matrix2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TableroLayout.createSequentialGroup()
                        .addComponent(Matrix3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Matrix4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Matrix5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TableroLayout.setVerticalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Matrix2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matrix0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matrix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Matrix3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Matrix5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Matrix4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Matrix6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matrix7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matrix8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 389, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTyped
        boardInput(evt);
    }//GEN-LAST:event_inputTyped

    private void boardInput(java.awt.event.KeyEvent evt){
        JTextField field;//Campo del tablero
        int valueLength;
        field = (JTextField) evt.getSource();
        valueLength = field.getText().length();
       
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || valueLength >0){
            evt.consume();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Matrix0;
    private javax.swing.JPanel Matrix1;
    private javax.swing.JPanel Matrix2;
    private javax.swing.JPanel Matrix3;
    private javax.swing.JPanel Matrix4;
    private javax.swing.JPanel Matrix5;
    private javax.swing.JPanel Matrix6;
    private javax.swing.JPanel Matrix7;
    private javax.swing.JPanel Matrix8;
    private javax.swing.JTextField P0_0;
    private javax.swing.JTextField P0_1;
    private javax.swing.JTextField P0_2;
    private javax.swing.JTextField P0_3;
    private javax.swing.JTextField P0_4;
    private javax.swing.JTextField P0_5;
    private javax.swing.JTextField P0_6;
    private javax.swing.JTextField P0_7;
    private javax.swing.JTextField P0_8;
    private javax.swing.JTextField P1_0;
    private javax.swing.JTextField P1_1;
    private javax.swing.JTextField P1_2;
    private javax.swing.JTextField P1_3;
    private javax.swing.JTextField P1_4;
    private javax.swing.JTextField P1_5;
    private javax.swing.JTextField P1_6;
    private javax.swing.JTextField P1_7;
    private javax.swing.JTextField P1_8;
    private javax.swing.JTextField P2_0;
    private javax.swing.JTextField P2_1;
    private javax.swing.JTextField P2_2;
    private javax.swing.JTextField P2_3;
    private javax.swing.JTextField P2_4;
    private javax.swing.JTextField P2_5;
    private javax.swing.JTextField P2_6;
    private javax.swing.JTextField P2_7;
    private javax.swing.JTextField P2_8;
    private javax.swing.JTextField P3_0;
    private javax.swing.JTextField P3_1;
    private javax.swing.JTextField P3_2;
    private javax.swing.JTextField P3_3;
    private javax.swing.JTextField P3_4;
    private javax.swing.JTextField P3_5;
    private javax.swing.JTextField P3_6;
    private javax.swing.JTextField P3_7;
    private javax.swing.JTextField P3_8;
    private javax.swing.JTextField P4_0;
    private javax.swing.JTextField P4_1;
    private javax.swing.JTextField P4_2;
    private javax.swing.JTextField P4_3;
    private javax.swing.JTextField P4_4;
    private javax.swing.JTextField P4_5;
    private javax.swing.JTextField P4_6;
    private javax.swing.JTextField P4_7;
    private javax.swing.JTextField P4_8;
    private javax.swing.JTextField P5_0;
    private javax.swing.JTextField P5_1;
    private javax.swing.JTextField P5_2;
    private javax.swing.JTextField P5_3;
    private javax.swing.JTextField P5_4;
    private javax.swing.JTextField P5_5;
    private javax.swing.JTextField P5_6;
    private javax.swing.JTextField P5_7;
    private javax.swing.JTextField P5_8;
    private javax.swing.JTextField P6_0;
    private javax.swing.JTextField P6_1;
    private javax.swing.JTextField P6_2;
    private javax.swing.JTextField P6_3;
    private javax.swing.JTextField P6_4;
    private javax.swing.JTextField P6_5;
    private javax.swing.JTextField P6_6;
    private javax.swing.JTextField P6_7;
    private javax.swing.JTextField P6_8;
    private javax.swing.JTextField P7_0;
    private javax.swing.JTextField P7_1;
    private javax.swing.JTextField P7_2;
    private javax.swing.JTextField P7_3;
    private javax.swing.JTextField P7_4;
    private javax.swing.JTextField P7_5;
    private javax.swing.JTextField P7_6;
    private javax.swing.JTextField P7_7;
    private javax.swing.JTextField P7_8;
    private javax.swing.JTextField P8_0;
    private javax.swing.JTextField P8_1;
    private javax.swing.JTextField P8_2;
    private javax.swing.JTextField P8_3;
    private javax.swing.JTextField P8_4;
    private javax.swing.JTextField P8_5;
    private javax.swing.JTextField P8_6;
    private javax.swing.JTextField P8_7;
    private javax.swing.JTextField P8_8;
    private javax.swing.JPanel Tablero;
    // End of variables declaration//GEN-END:variables
}
